### File variables
@PAP-HOST = pap-provider.127.0.0.1.nip.io:8080


### 01. Get the policy list
GET http://{{PAP-HOST}}/policy


### 02. Delete a policy
@02_POLICY-ID = smlehbdvmo

DELETE http://{{PAP-HOST}}/policy/{{02_POLICY-ID}}


### 03. Create a policy to allow any participant to read entities of a given type
@03_ENTITY-TYPE = EnergyReport
@03_ODRL-ASSIGNEE = vc:any
@03_ODRL-ACTION = odrl:read

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "ngsi-ld:entityType",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{03_ENTITY-TYPE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@id": "{{03_ODRL-ASSIGNEE}}"
        },
        "odrl:action": {
            "@id": "{{03_ODRL-ACTION}}"
        }
    }
}


### 04. Allow every authenticated participant to read product offerings
@04_RESOURCE = productOffering
@04_ODRL-ASSIGNEE = vc:any
@04_ODRL-ACTION = odrl:read

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "tmf:resource",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{04_RESOURCE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@id": "{{04_ODRL-ASSIGNEE}}"
        },
        "odrl:action": {
            "@id": "{{04_ODRL-ACTION}}"
        }
    }
}


### 05. Allow every authenticated participant to register as customer at the marketplace
@05_RESOURCE = organization
@05_ODRL-ASSIGNEE = vc:any
@05_ODRL-ACTION = tmf:create

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "tmf:resource",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{05_RESOURCE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@id": "{{05_ODRL-ASSIGNEE}}"
        },
        "odrl:action": {
            "@id": "{{05_ODRL-ACTION}}"
        }
    }
}


### 06. Allow the creation of product orders
@06_RESOURCE = productOrder
@05_ODRL-ASSIGNEE = vc:any
@05_ODRL-ACTION = tmf:create

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{ 
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "tmf:resource",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{06_RESOURCE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@id": "{{05_ODRL-ASSIGNEE}}"
        },
        "odrl:action": {
            "@id": "{{05_ODRL-ACTION}}"
        }
    }
}


### 07. Allow the creation of entities of a given type to authenticated participants with a given verifiable credentials type
@07_ENTITY-TYPE = K8SCluster
@07_ODRL-ACTION = odrl:use
@07_VC-TYPE = OperatorCredential

POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "ngsi-ld:entityType",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{07_ENTITY-TYPE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@type": "odrl:PartyCollection",
            "odrl:source": "urn:user",
            "odrl:refinement": {
                "@type": "odrl:Constraint",
                "odrl:leftOperand": {
                    "@id": "vc:type"
                },
                "odrl:operator": {
                    "@id": "odrl:hasPart"
                },
                "odrl:rightOperand": {
                    "@value": "{{07_VC-TYPE}}",
                    "@type": "xsd:string"
                }
            }
        },
        "odrl:action": {
            "@id": "{{07_ODRL-ACTION}}"
        }
    }
}


### Federation of brokers

### -- 08. Allow the creation of context source registrations
@08_ENTITY-TYPE = ContextSourceRegistration
@08_ODRL-ASSIGNEE = vc:any
@08_ODRL-ACTION = odrl:use


POST http://{{PAP-HOST}}/policy
Content-Type: application/json

{
    "@context": {
        "dc": "http://purl.org/dc/elements/1.1/",
        "dct": "http://purl.org/dc/terms/",
        "owl": "http://www.w3.org/2002/07/owl#",
        "odrl": "http://www.w3.org/ns/odrl/2/",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "skos": "http://www.w3.org/2004/02/skos/core#"
    },
    "@id": "https://mp-operation.org/policy/common/type",
    "@type": "odrl:Policy",
    "odrl:permission": {
        "odrl:assigner": {
            "@id": "https://www.mp-operation.org/"
        },
        "odrl:target": {
            "@type": "odrl:AssetCollection",
            "odrl:source": "urn:asset",
            "odrl:refinement": [
                {
                    "@type": "odrl:Constraint",
                    "odrl:leftOperand": "ngsi-ld:entityType",
                    "odrl:operator": {
                        "@id": "odrl:eq"
                    },
                    "odrl:rightOperand": "{{08_ENTITY-TYPE}}"
                }
            ]
        },
        "odrl:assignee": {
            "@id": "{{08_ODRL-ASSIGNEE}}"
        },
        "odrl:action": {
            "@id": "{{08_ODRL-ACTION}}"
        }
    }
}