### File variables
@TIL-HOST = til.127.0.0.1.nip.io:8080
@TIR-HOST = tir.127.0.0.1.nip.io:8080
@FEDERATOR-DID = did:key:zDnaeSxKtsMF4vuwDcTzjm2MyCpQvT8HoDM938dFCdPexhvpC
@FEDERATED-PROVIDER-A-DID = did:key:zDnaeoL9FquPRvvdXUtQKvCysPgeHDG44DvkeWuPcg3spZCMQ


### 01. Use TIR API to fetch the global trusted issuers list
GET http://{{TIR-HOST}}/v4/issuers


### 02. Use TIL API to register FEDERATOR participant to the Trust Anchor
POST http://{{TIL-HOST}}/issuer
Content-Type: application/json

{
    "did": "{{FEDERATOR-DID}}",
    "credentials": []
}


### 03. Use TIL API to register FEDERATED-PROVIDER-A participant to the Trust Anchor
POST http://{{TIL-HOST}}/issuer
Content-Type: application/json

{
    "did": "{{FEDERATED-PROVIDER-A-DID}}",
    "credentials": []
}


### 04. Unregister a participant from the Trust Anchor
@04_PARTICIPANT-DID = DID
DELETE http://{{TIL-HOST}}/issuer/{{04_PARTICIPANT-DID}}